### ISSUE TITLE
We need a way of reseting the user storage in the user interface

### ISSUE THREAD

**Issue by villares** [villares/faded-parsons-visual#1]
When examples change or in case the person wants to restart

**Comment by villares** [comment]
I was able to turn off completely the puzzle state storage so that a page refresh restores the original state, but I think this is not a good UX either...

**Comment by lucianoratamero** [comment]
done and pushed to `hack`. the easiest way to do it was to clear the storage and reload the page.
in my honest opinion, users don't really mind seeing the page reload when a `Reset` button is clicked, and it was getting VERY complicated to reset without realoading it, so I think this solution is **good enough** :]

**Comment by villares** [comment]
Wow! I missed this! I'll try to check it out. Thank you!

**Comment by villares** [comment]
wonderful, thank you!
