### ISSUE TITLE
Output result (pyp5js canvas) seems to be placed outside results area on first run

### ISSUE THREAD

**Issue by villares** [villares/faded-parsons-visual#4]
It looks like the first time the code is executed the result falls on the bottom left of the page.

**Comment by villares** [comment]
Misplaced canvas (first run):

![misplaced canvas](https://user-images.githubusercontent.com/3694604/208164199-d5ea37c4-3862-4db3-b12f-41516f054743.png)

Correct canvas position:

![correct canvas](https://user-images.githubusercontent.com/3694604/208164214-75d510f4-8079-4d97-844f-9086121dd522.png)

**Comment by villares** [comment]
Maybe, if it is not too much trouble, at some point I would like to try the result in the upper part of the page. Like, dividing the first section in two columns with the problem statement and image of the expected solution on the left and the canvas with the result of the puzzle on the right...

**Comment by lucianoratamero** [comment]
fixed and pushed to the `hack` branch.
@villares , could you please double check? if it's working for you, just close the issue :]

**Comment by villares** [comment]
Thank you, wonderful! 
I'll open an issue later on for us to rethink the layout, OK?
