### ISSUE TITLE
I don't know how to "build" this...

### ISSUE THREAD

**Issue by villares** [villares/faded-parsons-visual#5]
Cheers @lucianoratamero !

There is some **pyp5js** code in `dist/bundle.js`
And also in `js/sketch_runner.js`  (I'm not sure both are needed).

A quick looks and it seems that the `bundle.js` code is being used, but it is harder to edit/maintain... could we use https://github.com/villares/pyp5js/blob/develop/docs/py5mode/target/target_sketch.js ?

UPDATE: I see the "runCode()" part needs to be different... 
I have removed the `sketch-runner.js` file and nothing yet broke so... with your blessing I might as well close this!

**Comment by villares** [comment]
@lucianoratamero explained to me that `bundle.js` is probably "generated" in a build process.

So I brought back the `sketch-runner.js` and I'm trying to keep it in sync with the direct hacks on `bundle.js`. I guess I'll have to learn how to "build" this with dreadful *npn* etc...

Wish: Can someone write for me a step by step guide of how to build this?

**Comment by lucianoratamero** [comment]
@villares , i just pushed to the `hack` branch an improved version of the readme.

also, I noticed that python was only being used for serving the app, so I took the time to remove the need for people to install python by installing a local http server via npm.
with that, people only need to have nodejs installed and run `npm install` and `npm run dev` to run the project.

please ping me on telegram if you disagree or have suggestions about these changes.

**Comment by villares** [comment]
Cheers @lucianoratamero!

I tried the `npm run dev` and got some errors:

```
> dev
> npm-run-all --parallel start watch

sh: line 1: npm-run-all: command not found
```

I tried to install `npm-run-all` and then got a similar error for `rollup` and `http-server` ...
so I tried installing them too.

Now I think I see the project fine, but just for the record I get some warnings:

```
(node:117326) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
[!] RollupError: Node tried to load your configuration file as CommonJS even though it is likely an ES module. To resolve this, change the extension of your configuration to ".mjs", set "type": "module" in your package.json file or pass the "--bundleConfigAsCjs" flag.

Original error: Cannot use import statement outside a module
https://rollupjs.org/command-line-interface/#bundleconfigascjs
/home/villares/GitHub/faded-parsons-visual/rollup.config.js:1
import resolve from '@rollup/plugin-node-resolve';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1126:15)
    at Module._compile (node:internal/modules/cjs/loader:1162:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
```

**Comment by villares** [comment]
Hmm, I'm afraid I'll need some help from you when you have the time,  `npm run build` didn't work for me:

```
[villares@alexandre-xps179720 faded-parsons-visual]$ npm run build

> build
> rollup -c

(node:119305) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
[!] RollupError: Node tried to load your configuration file as CommonJS even though it is likely an ES module. To resolve this, change the extension of your configuration to ".mjs", set "type": "module" in your package.json file or pass the "--bundleConfigAsCjs" flag.

Original error: Cannot use import statement outside a module
https://rollupjs.org/command-line-interface/#bundleconfigascjs
/home/villares/GitHub/faded-parsons-visual/rollup.config.js:1
import resolve from '@rollup/plugin-node-resolve';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1126:15)
    at Module._compile (node:internal/modules/cjs/loader:1162:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
```

**Comment by villares** [comment]
Solved with `npm audit fix --force` I think.
